config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about'
    resources :items, only:[:index, :show]
    get '/customers/my_page' => 'customers#show'
    get '/customers/edit' => 'customers#edit'
    patch '/customers' => 'customers#update'
    get 'customers/edit' => 'public/customers#edit'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :destroy_all, :create]
    get '/orders/complete' => 'orders#complete'
    resources :orders, only:[:new, :create, :index, :show]
    post '/orders/confirm' => 'orders#confirm'
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations',
    passwords: 'admin/passwords'
  }

  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    registrations: 'public/customers/registrations',
    passwords: 'public/customers/passwords'
  }

  namespace :admin do
    root to: "homes#top"
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  attachment :image

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre, optional: true

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method:{
    クレジットカード: 0,
    銀行振込: 1
  }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  before_action :authenticate_admin!, except: [:top]
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @orders = Order.all.page(params[:page]).reverse_order
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!, except: [:top, :index]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item[:id])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item[:id])
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :created_at, :updated_at)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!, except: [:top]

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :address, :postal_code, :telephone_number ])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/items/edit.html.erb
<%= render 'admin/admin' %>

<div class="container mt-5">

 <h2 class="row">商品編集</h2>

  <%= form_with model: @item, url: admin_item_path(@item), local:true do |f| %>

   <div class="field row mt-3 ml-3 mt-5">
    <label class="col-md-2">商品画像</label>
    <div class="col">
     <%= f.attachment_field :image %>
    </div>
   </div>

   <div class="field row mt-3 ml-3 mt-5">
    <label class="name col-md-2">商品名</label>
    <div class="col">
     <%= f.text_field :name, autofocus: true, id:"name" %>
    </div>
   </div>

   <div class="field row mt-3 ml-3 mt-5">
    <label class="introduction col-md-2">商品説明</label>
    <div class="col">
     <%= f.text_field :introduction, autofocus: true, id:"introduction" %>
    </div>
   </div>

   <div class="field row mt-3 ml-3 mt-5">
    <label class="price col-md-2">税抜価格</label>
    <div class="col">
     <%= f.text_field :price, autofocus: true, id:"price" %> 円
    </div>
   </div>

   <div class="field row mt-3 ml-3 mt-5">
    <label class="price col-md-2"></label>
    <div class="col">
     <%= f.submit "変更を保存", class: "btn btn-outline-primary" %>
    </div>
   </div>

  <% end %>

</div>

app/views/admin/items/index.html.erb
<%= render 'admin/admin' %>

<div class="container mt-5">

  <h2 class="row">商品一覧</h2>

  <div class="row mt-5">
    <table class="table table-striped col mr-5">
      <thead>
        <tr>
          <th class="text-center">商品ID</th>
          <th class="text-center">商品名</th>
          <th class="text-center">税抜価格</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td class="text-center"><%= item.id %></td>
            <td class="text-center"><%= link_to item.name, admin_item_path(item), class: "text-dark border-bottom border-dark" %></td>
            <td class="text-center"><%= item.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row mt-5">
    <%= link_to "商品新規登録", new_admin_item_path, class: "btn btn-outline-primary" %>
  </div>

</div>

app/views/admin/items/new.html.erb
<%= render 'admin/admin' %>

<div class="container mt-5">

  <h1>商品新規登録ページ</h1>

  <%= form_with model: @item, url: admin_items_path, local:true do |f| %>

  <div class="field row mt-3 ml-3 mt-5">
   <label class="col-md-2">商品画像</label>
   <div class="col">
    <%= f.attachment_field :image %>
   </div>
  </div>

  <div class="field row mt-3 ml-3 mt-5">
   <label for="name" class="col-md-2">商品名</label>
   <div class="col">
    <%= f.text_field :name, autofocus: true, id:"name" %>
   </div>
  </div>

  <div class="field row mt-3 ml-3 mt-5">
   <label for="introduction" class="col-md-2">商品説明</label>
   <div class="col">
    <%= f.text_field :introduction, autofocus: true, id:"introduction" %>
   </div>
  </div>

  <div class="field row mt-3 ml-3 mt-5">
   <label for="price" class="col-md-2">税抜価格</label>
   <div class="col">
    <%= f.text_field :price, autofocus: true, id:"price" %> 円
   </div>
  </div>

  <div class="row mt-3 ml-3 mt-5">
   <div class="col-md-2"></div>
   <div class="col">
    <%= f.submit "新規登録", class:"btn btn-outline-primary" %>
   </div>
  </div>

 <% end %>

</div>

app/views/admin/items/show.html.erb
<%= render 'admin/admin' %>

<div class="container mt-5">

  <h2 class="row">商品詳細</h2>

  <div class="row mt-5">
    <table class="table table-striped col mr-5">
      <thead>
        <tr>
          <th class="text-center"></th>
          <th class="text-center">商品名</th>
          <th class="text-center">商品説明</th>
          <th class="text-center">税込価格（税抜価格）</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td class="text-center"><%= attachment_image_tag @item, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
            <td class="text-center"><%= @item.name %></td>
            <td class="text-center"><%= @item.introduction %></td>
            <td class="text-center"><%= (@item.price*1.1).to_i %>円(<%= @item.price %>円)</td>
          </tr>
      </tbody>
    </table>
  </div>

  <div class=" row mt-5">
    <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-outline-primary" %>
  </div>

</div>

app/views/admin/orders/show.html.erb
<%= render 'admin/admin' %>

<div class="container mt-5">

  <h2 class="row">注文履歴詳細</h2>

  <div class="field row mt-3 ml-3 mt-5">
    <div class="col-md-2">購入者</div>
    <div class="col"><%= link_to @order.customer.last_name + @order.customer.first_name, admin_customer_path(@order.customer), class:"text-dark border-bottom border-dark" %></div>
  </div>

  <div class="field row mt-3 ml-3 mt-3">
    <div class="col-md-2">注文日</div>
    <div class="col"><%= @order.created_at.to_s(:datetime_jp) %></div>
  </div>

  <div class="field row mt-3 ml-3 mt-3">
    <div class="col-md-2">配送先</div>
    <div class="col"><%= "〒" + @order.customer.postal_code + "　" + @order.customer.address + "　" + @order.customer.last_name + @order.customer.first_name %></div>
  </div>

  <div class="field row mt-3 ml-3 mt-3">
    <div class="col-md-2">支払方法</div>
    <div class="col"><%= @order.payment_method %></div>
  </div>

  <div class="row mt-5 ml-3">
    <table class="table table-striped col mr-5">
      <thead>
        <tr>
          <th>商品</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
        </tr>
      </thead>
      <tbody>
        <% @order_details.each do |od| %>
        <tr>
          <td><%= od.item.name %></td>
          <td><%= (od.item.price * 1.1).to_i.to_s(:delimited) %></td>
          <td><%= od.amount %></td>
          <td><%= (od.item.price * 1.1 * od.amount).to_i.to_s(:delimited) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class-"col">
      <div class="row">
        <div>
          商品合計<%= "　　　" + (@order.total_payment - 800).to_i.to_s(:delimited) %>円
        </div>
      </div>
      <div class="row">
        <div>
          <pr>送料　　　　　<%= 800 %>円</pr>
        </div>
      </div>
      <div class="row">
        <div>
          請求金額合計<%= "　" + @order.total_payment.to_i.to_s(:delimited) %>円
        </div>
      </div>
    </div>
  </div>

</div>