config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about'
    resources :items, only:[:index, :show]
    get '/customers/my_page' => 'customers#show'
    get '/customers/edit' => 'customers#edit'
    patch '/customers' => 'customers#update'
    get 'customers/edit' => 'public/customers#edit'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :destroy_all, :create]
    get '/orders/complete' => 'orders#complete'
    resources :orders, only:[:new, :create, :index, :show]
    post '/orders/confirm' => 'orders#confirm'
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations',
    passwords: 'admin/passwords'
  }

  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    registrations: 'public/customers/registrations',
    passwords: 'public/customers/passwords'
  }

  namespace :admin do
    root to: "homes#top"
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  attachment :image

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre, optional: true

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method:{
    クレジットカード: 0,
    銀行振込: 1
  }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!, except: [:top]

  def index
    @customers = Customer.all.page(params[:page]).order(:id)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  before_action :authenticate_admin!, except: [:top]
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @orders = Order.all.page(params[:page]).reverse_order
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!, except: [:top, :index]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item[:id])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item[:id])
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :created_at, :updated_at)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!, except: [:top]

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :address, :postal_code, :telephone_number ])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<%= render 'admin/admin' %>

<div class="container mt-5">

 <h2 class="row">
   <%= @customer.last_name + @customer.first_name %>さんの会員情報編集
 </h2>

 <div class="row mt-5">
  <label class="col-md-2">会員ID</label>
  <div class="col">
    <%= @customer.id %>
  </div>
 </div>

 <%= form_with model: @customer, url: admin_customer_path(@customer), local:true do |f| %>

   <div class="row mt-3">
    <label for="name" class="col-md-2">氏名</label>
    <div class="col">
     <%= f.text_field :last_name, autofocus: true, id:"name" %>
     <%= f.text_field :first_name, autofocus: true, id:"name" %>
    </div>
   </div>

   <div class="row mt-3">
    <label for="kana" class="col-md-2">フリガナ</label>
    <div class="col">
     <%= f.text_field :last_name_kana, autofocus: true, id:"kana" %>
     <%= f.text_field :first_name_kana, autofocus: true, id:"kana" %>
    </div>
   </div>

   <div class="row mt-3">
    <label for="postal_code" class="col-md-2">郵便番号</label>
    <div class="col">
     <%= f.text_field :postal_code, autofocus: true, id:"postal_code" %>
    </div>
   </div>

   <div class="row mt-3">
    <label for="address" class="col-md-2">住所</label>
    <div class="col">
     <%= f.text_field :address, autofocus: true, id:"address" %>
    </div>
   </div>

   <div class="row mt-3">
    <label for="telephone_number" class="col-md-2">電話番号</label>
    <div class="col">
     <%= f.text_field :telephone_number, autofocus: true, id:"telephone_number" %>
    </div>
   </div>

   <div class="row mt-3">
    <label for="email" class="col-md-2">メールアドレス</label>
    <div class="col">
     <%= f.email_field :email, autofocus: true, id:"email" %>
    </div>
   </div>

   <div class="row mt-3">
    <label for="is_active" class="col-md-2">会員ステータス</label>
    <div class="col">
     <% if @customer.is_active == true %>
      <%= f.radio_button :is_active, :true, checked: true %>
      <%= f.label :is_active, "有効" %>
      <%= f.radio_button :is_active, :false %>
      <%= f.label :is_active, "退会" %>
     <% else %>
      <%= f.radio_button :is_active, :true %>
      <%= f.label :is_active, "有効" %>
      <%= f.radio_button :is_active, :false, checked: true %>
      <%= f.label :is_active, "退会" %>
     <% end %>
    </div>
   </div>

   <div class="row mt-5">
    <div class="col-md-2"></div>
    <div class="col">
     <%= f.submit "変更を保存", class:"btn btn-outline-success" %>
    </div>
   </div>

 <% end %>

</div>

app/views/admin/customers/index.html.erb
<%= render 'admin/admin' %>

<div class="container mt-5">

  <h2>会員一覧</h2>

  <table class="table table-striped col mr-5">
    <thead>
      <tr>
        <th class="text-center">会員ID</th>
        <th class="text-center">氏名</th>
        <th class="text-center">メールアドレス</th>
        <th class="text-center">ステータス</th>
      </tr>
    </thead>
    <tbody>
     <% @customers.each do |customer| %>
     <tr>
      <td class="text-center"><%= customer.id %></td>
      <td class="text-center"><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer), class: "text-dark border-bottom border-dark" %></td>
      <td class="text-center"><%= customer.email %></td>
      <td class="text-center">
        <% if customer.is_active == false %>
         <div>退会</div>
        <% else %>
         <div>有効</div>
        <% end %>
      </td>
     </tr>
     <% end %>
    </tbody>
  </table>
  <%= paginate @customers %>

</div>

app/views/admin/customers/show.html.erb
<%= render 'admin/admin' %>

<div class="container mt-5">

  <h2>
    <%= @customer.last_name + @customer.first_name %>さんの会員詳細
  </h2>

  <div class="row mt-5">
    <div class="col">会員ID</div>
    <div class="col">
      <%= @customer.id %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">氏名</div>
    <div class="col">
      <%= @customer.last_name + @customer.first_name %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">フリガナ</div>
    <div class="col">
      <%= @customer.last_name_kana + @customer.first_name_kana %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">郵便番号</div>
    <div class="col">
      <%= @customer.postal_code %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">住所</div>
    <div class="col">
      <%= @customer.address %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">電話番号</div>
    <div class="col">
      <%= @customer.telephone_number %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">メールアドレス</div>
    <div class="col">
      <%= @customer.email %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">会員ステータス</div>
    <div class="col">
      <% if @customer.is_active == false %>
        <div>退会</div>
      <% else %>
        <div>有効</div>
      <% end %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col text-center">
      <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-outline-success" %>
    </div>
    <div class="col text-center">
      <%= link_to "注文履歴一覧を見る", admin_root_path, class:"btn btn-outline-primary" %>
    </div>
  </div>

</div>